@Presentation_HostAddress = http://localhost:5200

GET {{Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###

# Get all users
GET {{Presentation_HostAddress}}/users
Accept: application/json

###

# Create a new user
POST {{Presentation_HostAddress}}/users
Content-Type: application/json

{
  "name": "John Doe"
}

###

# Get user by ID
GET {{Presentation_HostAddress}}/users/1
Accept: application/json

###

# Update user
PUT {{Presentation_HostAddress}}/users/1
Content-Type: application/json

{
  "name": "Jane Doe"
}

###

# Delete user
DELETE {{Presentation_HostAddress}}/users/1

###
